### ISSUE TITLE
Download the client without knowing the exact version

### ISSUE THREAD

**Issue by amd64fox** [nick-botticelli/SpotifyUpgradeFinder#2]
Hello, thank you for the useful application, such a question, how can you download the client without knowing its exact version?
For example, I know that version `1.1.67` has been released, but I don’t know what goes next `1.67.XXX.XXXXXXXXX`
Is this even possible?

**Comment by nick-botticelli** [comment]
The only reliable ways I have found to determine the Spotify version string is to see if it's listed on https://www.spotify.com/us/opensource/ or to intercept the URL when attempting a Spotify upgrade. That version isn't currently listed, so you can either wait or intercept it yourself (with a tool such as Fiddler).

**Comment by amd64fox** [comment]
Yes, I know this site, but it is not updated very often.
The idea of intercepting url is interesting, but my region is one of the last to be updated, and I don't want to connect with vpn.
Thanks for the answer.
